### ekf config file ###
ekf_filter_node:
    ros__parameters:
      use_sim_time: false
      frequency: 15.0
      sensor_timeout: 0.1

      print_diagnostics: true # --- TODO: FOR testing

      odom_frame: odom
      base_link_frame: base_footprint
      world_frame: odom
      map_frame: map


      two_d_mode: true

      #x     , y     , z,
      #roll  , pitch , yaw,
      #vx    , vy    , vz,
      #vroll , vpitch, vyaw,
      #ax    , ay    , az

      odom0: /odom_raw
      odom0_config: [false, false, false,
                    false, false, false,
                    true, true, false,
                    false, false, true,
                    false, false, false]

      odom0_queue_size: 10

      odom0_differential: false
      odom0_relative: false

      imu0: /imu/data

      # [ X , Y , Z ,
      #  Roll, Pitch, Yaw,
      #  Vx, Vy, Vz,
      #  Vroll, Vpitch, Vyaw,
      #  Ax, Ay, Az ]
      imu0_config: [false, false, false,
                    false, false, true,
                    false, false, false,
                    false, false, true,
                    true, true, true]

      imu0_differential: true
      imu0_relative: false
      imu0_queue_size: 10
      imu0_pose_rejection_threshold: 20.0
      imu0_twist_rejection_threshold: 1.542
      imu0_linear_acceleration_rejection_threshold: 10.0